version: '3.6'

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: shrishail
      POSTGRES_PASSWORD: test1234
      POSTGRES_HOST: postgres
      POSTGRES_DB: smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/smart-brain-api


  # Postgres DB
  postgres:
    container_name: postgresdb
    environment:
      POSTGRES_USER: shrishail
      POSTGRES_PASSWORD: test1234
      POSTGRES_HOST: postgres
      POSTGRES_DB: smart-brain-docker
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"
    